name: Update My Github Status in README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

env:
  GITHUB_NAME: pacoxu-bot
  GITHUB_EMAIL: paco2023@163.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My GitHub Status
        uses: pacoxu/github-readme-stats@main
        with:
          REPOS_NUM: 3
          STARRED_NUM: 3
#           WITH_STARED: false
#           TELEGRAM_TOKEN: ${{ secrets.TELE_TOKEN }}
#           TELEGRAM_CHAT_ID: ${{ secrets.TELE_CHAT_ID }}
      - name: Push README
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'docs: update readme.md'
          git push
